[gcp_service_account]
type = "service_account"
project_id = "inventario-app-123456"
private_key_id = "abc123def456ghi789"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC4g8sQ6dP7m8Kp\nTUESTE... (tu clave aqu√≠)\n-----END PRIVATE KEY-----"
client_email = "inventario@appspot.gserviceaccount.com"
client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/inventario%40appspot.gserviceaccount.com"
universe_domain = "googleapis.com"